// Copy for the NeuroViu Edge AI explainer, status card and technical demo.
import type { Lang } from "./bridge";

export const EDGE = {
  en: {
    tagline: "Small AI for frontline care.",
    by: "An offline intelligence system by NeuroViu Labs",
    pipeTitle: "How NeuroViu Edge AI Works",
    pipeline: [
      ["Patient Voice / Text", "English or French natural-language encounter input."],
      ["NeuroViu Edge AI", "A lightweight language model processes the encounter directly on the device."],
      ["Grounding & Safety Layer", "AI-generated information is checked against the patient's original words. Unsupported information is rejected or replaced with safer structured extraction."],
      ["Human Review", "The frontline health worker reviews, edits and explicitly approves the draft. AI never makes the final clinical decision."],
      ["Local-First Health Record", "Approved encounters remain available on the device without internet connectivity."],
      ["Sync When Connected", "Records can later join a store-and-forward sync workflow. Sync is simulated in this prototype."],
    ],
    simulated: "Simulated",
    statusTitle: "NeuroViu Edge AI Status",
    status: { processing: "Processing", onDevice: "On-device", model: "Model", net: "Internet required for inference", cloud: "Patient text sent to cloud AI", grounding: "Grounding safeguard", active: "Active", human: "Human approval", required: "Required", dx: "Diagnostic AI", no: "No", accel: "Acceleration" },
    basicTitle: "Basic offline processing mode",
    basicNote: "The AI model is not loaded. Drafts use simple keyword rules on this device — this is not model-based AI.",
    loadingNote: "AI model is loading. Until it is ready, drafts use basic keyword rules.",
    steps: ["Processing locally", "Structuring encounter", "Checking output against patient report", "Preparing draft for human review"],
    groundingApplied: "Grounding safeguard applied — unsupported AI-generated information was excluded.",
    demoBtn: "View Technical Demo",
    demoTitle: "Technical Demo",
    demoIntro: "NeuroViu Bridge is not a healthcare chatbot. It is an offline-first, locally running, grounded, human-reviewed Small AI system for low-connectivity care.",
    features: [
      ["Offline-first PWA", "Installable; service worker caches the app so it opens without internet.", "real"],
      ["Local small language model", "Phones: SmolLM2-135M-Instruct (INT8, ~133 MiB). Computers: Qwen2.5-0.5B-Instruct (quantized; ~461 MiB q4f16 with WebGPU, ~750 MiB q4 on CPU). Downloaded once and cached for on-device inference.", "real"],
      ["English + French", "Input, prompts, drafts and interface in both languages.", "real"],
      ["On-device inference", "Transformers.js / ONNX Runtime Web in a background worker. Phones always use CPU (WebAssembly); computers use WebGPU where supported, with CPU fallback. No internet needed after preparation.", "real"],
      ["Grounding safeguard", "Model output is checked word-by-word against the patient's text; unsupported parts are dropped.", "real"],
      ["Human-in-the-loop approval", "Nothing is saved until the health worker reviews and ticks the approval box.", "real"],
      ["Persistent local storage", "Encounters are kept in the device's database (IndexedDB) across restarts.", "real"],
      ["Store-and-forward architecture", "Records queue as “Pending sync”. The sync step itself is simulated — no server.", "sim"],
      ["No cloud LLM required", "Core AI processing never sends patient text to a cloud AI service.", "real"],
      ["Danger-sign flag & fallback", "Emergency detection and the backup extractor use deterministic keyword rules on purpose.", "rule"],
    ] as [string, string, "real" | "sim" | "rule"][],
    tags: { real: "Working", sim: "Simulated", rule: "Rule-based" },
    limitsTitle: "Prototype limitations",
    limits: [
      "One-time AI model download: about 133 MiB on phones; on computers about 461 MiB (WebGPU) or 750 MiB (CPU).",
      "CPU inference may be slow on devices without WebGPU.",
      "Synchronization is simulated in the current prototype.",
      "Deterministic rules are intentionally used for selected safety behaviors.",
      "This prototype does not diagnose disease or recommend treatment.",
    ],
  },
  fr: {
    tagline: "Une petite IA pour les soins de première ligne.",
    by: "Un système d'intelligence hors ligne par NeuroViu Labs",
    pipeTitle: "Comment fonctionne NeuroViu Edge AI",
    pipeline: [
      ["Voix / texte du patient", "Saisie de la consultation en langage naturel, en anglais ou en français."],
      ["NeuroViu Edge AI", "Un modèle de langage léger traite la consultation directement sur l'appareil."],
      ["Ancrage et sécurité", "Les informations générées sont vérifiées contre les mots du patient. Ce qui n'est pas justifié est rejeté ou remplacé par une extraction structurée plus sûre."],
      ["Vérification humaine", "L'agent de santé vérifie, corrige et approuve explicitement le brouillon. L'IA ne prend jamais la décision clinique."],
      ["Dossier local d'abord", "Les consultations approuvées restent disponibles sur l'appareil sans internet."],
      ["Synchro à la connexion", "Les dossiers pourront rejoindre un flux « stocker puis transmettre ». La synchro est simulée dans ce prototype."],
    ],
    simulated: "Simulé",
    statusTitle: "État de NeuroViu Edge AI",
    status: { processing: "Traitement", onDevice: "Sur l'appareil", model: "Modèle", net: "Internet requis pour l'inférence", cloud: "Texte patient envoyé à une IA en ligne", grounding: "Garde-fou d'ancrage", active: "Actif", human: "Approbation humaine", required: "Requise", dx: "IA diagnostique", no: "Non", accel: "Accélération" },
    basicTitle: "Mode de traitement hors ligne basique",
    basicNote: "Le modèle d'IA n'est pas chargé. Les brouillons utilisent des règles par mots-clés — ce n'est pas une IA à modèle.",
    loadingNote: "Le modèle se charge. En attendant, les brouillons utilisent des règles par mots-clés.",
    steps: ["Traitement local", "Structuration de la consultation", "Vérification par rapport aux mots du patient", "Préparation du brouillon pour vérification"],
    groundingApplied: "Garde-fou d'ancrage appliqué — des informations générées non justifiées ont été exclues.",
    demoBtn: "Voir la démo technique",
    demoTitle: "Démo technique",
    demoIntro: "NeuroViu Bridge n'est pas un chatbot de santé. C'est un système de petite IA hors ligne, local, ancré et vérifié par un humain, pour les soins à faible connectivité.",
    features: [
      ["PWA hors ligne d'abord", "Installable ; le service worker met l'app en cache pour l'ouvrir sans internet.", "real"],
      ["Petit modèle de langage local", "Téléphones : SmolLM2-135M-Instruct (INT8, ~133 Mio). Ordinateurs : Qwen2.5-0.5B-Instruct (quantifié ; ~461 Mio q4f16 avec WebGPU, ~750 Mio q4 sur CPU). Téléchargé une fois et mis en cache pour l'inférence sur l'appareil.", "real"],
      ["Anglais + français", "Saisie, consignes, brouillons et interface dans les deux langues.", "real"],
      ["Inférence sur l'appareil", "Transformers.js / ONNX Runtime Web en arrière-plan. Les téléphones utilisent toujours le CPU (WebAssembly) ; les ordinateurs utilisent WebGPU si possible, sinon le CPU. Aucun internet requis après la préparation.", "real"],
      ["Garde-fou d'ancrage", "La sortie du modèle est vérifiée mot à mot contre le texte du patient ; le reste est écarté.", "real"],
      ["Approbation humaine", "Rien n'est enregistré avant que l'agent vérifie et coche la case d'approbation.", "real"],
      ["Stockage local persistant", "Les consultations restent dans la base de l'appareil (IndexedDB) après redémarrage.", "real"],
      ["Architecture stocker-transmettre", "Les dossiers attendent « En attente de synchro ». La synchro elle-même est simulée — pas de serveur.", "sim"],
      ["Aucun LLM en ligne requis", "Le traitement IA essentiel n'envoie jamais le texte patient à une IA en ligne.", "real"],
      ["Signes de danger et secours", "La détection d'urgence et l'extracteur de secours utilisent volontairement des règles fixes.", "rule"],
    ] as [string, string, "real" | "sim" | "rule"][],
    tags: { real: "Fonctionnel", sim: "Simulé", rule: "Par règles" },
    limitsTitle: "Limites du prototype",
    limits: [
      "Téléchargement unique du modèle : environ 133 Mio sur téléphone ; sur ordinateur environ 461 Mio (WebGPU) ou 750 Mio (CPU).",
      "L'inférence sur CPU peut être lente sans WebGPU.",
      "La synchronisation est simulée dans ce prototype.",
      "Des règles fixes sont volontairement utilisées pour certains comportements de sécurité.",
      "Ce prototype ne diagnostique pas et ne recommande aucun traitement.",
    ],
  },
} as const;

export const edge = (l: Lang) => EDGE[l];
